### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by andrewlangston** [elibretti/Earthy#2]
Hey Lizzy! Good work on your sample state. Just one comment to begin: 

- [x] It looks like the `shoppingCart` slice of state holds multiple objects. Are these each individual carts? Do they only hold one type of product, or can they hold many? If so, we'll need to bulk these out to allow for multiple quantities of multiple products.

Let me know if that makes sense!

**Comment by elibretti** [comment]
The way I was thinking about it was that each one of the objects is a "shopping cart item". So there is only 1 shopping cart at a given time, and it always belongs to the current user. The cart holds "shopping cart items" that can only be 1 product and basically just holds a quantity

**Comment by andrewlangston** [comment]
Got it - that sounds good. Closing this issue.
